# Generated by Django 5.0.9 on 2025-01-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blast_request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="blastn_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="database",
            name="blastp_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
