# Generated by Django 5.1.3 on 2025-01-14 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genhome', '0002_annotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fasequence',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fa_sequences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fasequence',
            name='status',
            field=models.CharField(choices=[('Full Genome', 'Full Genome'), ('Coding DNA Sequence', 'Coding DNA Sequence'), ('Peptide Sequence', 'Peptide Sequence')], default='Coding DNA Sequence', max_length=50),
        ),
    ]
