# Generated by Django 5.0.9 on 2025-01-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genhome', '0003_genome_geneprotein'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneProtein',
        ),
        migrations.DeleteModel(
            name='Genome',
        ),
    ]
