# Generated by Django 5.1.3 on 2025-01-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genhome', '0003_annotation_owner_fasequence_owner_fasequence_status'),
        ('genhome', '0004_delete_geneprotein_delete_genome'),
    ]

    operations = [
    ]
