# Generated by Django 5.1.3 on 2025-01-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genhome', '0004_delete_annotation'),
        ('genhome', '0005_merge_20250116_1402'),
    ]

    operations = [
    ]
