# Generated by Django 5.1.3 on 2025-01-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genhome", "0006_merge_0004_delete_annotation_0005_merge_20250116_1402"),
    ]

    operations = [
        migrations.AddField(
            model_name="fasequence",
            name="features_names",
            field=models.TextField(
                default="chromosome|gene|transcript|gene_biotype|transcript_byotype|gene_symbol|description"
            ),
        ),
        migrations.AddField(
            model_name="fasequence",
            name="features_val",
            field=models.TextField(
                default="non defini|non defini|non defini|non defini|non defini|non defini|non defini"
            ),
        ),
    ]
