# Generated by Django 5.1.3 on 2025-01-21 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genhome', '0006_merge_0004_delete_annotation_0005_merge_20250116_1402'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasequence',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_sequences', to=settings.AUTH_USER_MODEL),
        ),
    ]
