# Generated by Django 5.1.3 on 2025-01-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genhome", "0007_fasequence_features_names_fasequence_features_val"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fasequence",
            name="features_names",
            field=models.TextField(
                default="chromosome|gene|transcript|gene_biotype|transcript_biotype|gene_symbol|description"
            ),
        ),
    ]
