# Generated by Django 5.1.3 on 2025-01-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genhome", "0008_alter_fasequence_features_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fasequence",
            name="features_names",
        ),
        migrations.RemoveField(
            model_name="fasequence",
            name="features_val",
        ),
    ]
