# Generated by Django 5.1.3 on 2025-01-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genhome", "0009_remove_fasequence_features_names_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fasequence",
            name="identifiant",
            field=models.CharField(default="Non defini", max_length=100),
        ),
    ]
