# Generated by Django 5.1.3 on 2025-02-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genhome', '0007_alter_fasequence_owner'),
        ('genhome', '0010_fasequence_identifiant'),
    ]

    operations = [
    ]
