# Generated by Django 5.1.3 on 2025-02-05 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0006_alter_genome_name"),
        ("genhome", "0010_fasequence_identifiant"),
    ]

    operations = [
        migrations.AddField(
            model_name="fasequence",
            name="genome",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sequence",
                to="annotation.genome",
            ),
        ),
    ]
