# Generated by Django 5.1.3 on 2025-02-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genhome", "0011_fasequence_genome"),
        ("genhome", "0011_merge_20250203_1539"),
    ]

    operations = []
