# Generated by Django 5.1.3 on 2025-02-04 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0005_alter_genome_name"),
        ("genhome", "0012_alter_fasequence_genome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fasequence",
            name="genome",
            field=models.ForeignKey(
                default="non defini",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Genome",
                to="annotation.genome",
            ),
        ),
    ]
