# Generated by Django 5.1.3 on 2025-02-04 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genhome", "0014_alter_fasequence_genome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fasequence",
            name="genome",
        ),
    ]
