# Generated by Django 5.1.3 on 2025-02-06 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('chromosome', 'chromosome'), ('gene', 'gene'), ('transcript', 'transcript'), ('gene_biotype', 'gene_biotype'), ('transcript_biotype', 'ranscript_biotype'), ('gene_symbol', 'gene_symbol')], max_length=100)),
                ('value', models.TextField(default='non defini')),
            ],
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='non defini', max_length=100)),
                ('annotation_state', models.CharField(choices=[('in_progress', 'in progress'), ('fully', 'fully')], default='in_progress', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Attente'), ('V', 'Validé'), ('R', 'Refusé')], default='A', max_length=24)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
