# Generated by Django 5.1.3 on 2025-01-23 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0001_initial"),
        ("genhome", "0008_alter_fasequence_features_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("chromosome", "chromosome"),
                            ("gene", "gene"),
                            ("transcript", "transcript"),
                            ("gene_biotype", "gene_biotype"),
                            ("transcript_biotype", "ranscript_biotype"),
                            ("gene_symbol", "gene_symbol"),
                            ("description", "description"),
                        ],
                        max_length=100,
                    ),
                ),
                ("value", models.TextField(default="non defini")),
                (
                    "owner",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature",
                        to="genhome.fasequence",
                    ),
                ),
            ],
        ),
    ]
