# Generated by Django 5.1.3 on 2025-01-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0002_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="status",
            field=models.CharField(
                choices=[
                    ("chromosome", "chromosome"),
                    ("gene", "gene"),
                    ("transcript", "transcript"),
                    ("gene_biotype", "gene_biotype"),
                    ("transcript_biotype", "ranscript_biotype"),
                    ("gene_symbol", "gene_symbol"),
                ],
                max_length=100,
            ),
        ),
    ]
