# Generated by Django 5.1.3 on 2025-02-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_alter_feature_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='status',
            field=models.CharField(choices=[('A', 'Attente'), ('V', 'Validé'), ('R', 'Refusé')], default='A', max_length=24),
        ),
    ]
