# Generated by Django 5.1.3 on 2025-02-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0003_alter_feature_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Non defini", max_length=100)),
                (
                    "annotation_state",
                    models.CharField(
                        choices=[("in_progress", "in progress"), ("fully", "fully")],
                        default="in_progress",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
