# Generated by Django 5.1.3 on 2025-02-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0004_genome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genome",
            name="name",
            field=models.CharField(default=1, max_length=100),
        ),
    ]
