# Generated by Django 5.1.3 on 2025-02-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0005_alter_genome_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genome",
            name="name",
            field=models.CharField(default="non defini", max_length=100),
        ),
    ]
