# Generated by Django 5.1.3 on 2025-02-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0004_annotation_status"),
        ("annotation", "0006_alter_genome_name"),
    ]

    operations = []
