# Generated by Django 5.1.3 on 2025-01-21 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfouser',
            name='role',
            field=models.CharField(choices=[('Attente', 'Attente'), ('Lecteur', 'Lecteur'), ('Annotateur', 'Annotateur'), ('Validateur', 'Validateur'), ('Admin', 'Admin')], default='Admin', max_length=24),
        ),
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('Attente', 'Attente'), ('Lecteur', 'Lecteur'), ('Annotateur', 'Annotateur'), ('Validateur', 'Validateur'), ('Admin', 'Admin')], default='Lecteur', max_length=24)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
