# Generated by Django 5.1.3 on 2025-01-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_bioinfouser_role_rolerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinfouser',
            name='role',
            field=models.CharField(choices=[('AT', 'Attente'), ('LE', 'Lecteur'), ('AN', 'Annotateur'), ('VA', 'Validateur'), ('AD', 'Admin')], default='AD', max_length=24),
        ),
        migrations.AlterField(
            model_name='rolerequest',
            name='requested_role',
            field=models.CharField(choices=[('AT', 'Attente'), ('LE', 'Lecteur'), ('AN', 'Annotateur'), ('VA', 'Validateur'), ('AD', 'Admin')], default='LE', max_length=24),
        ),
    ]
