# Generated by Django 5.1.3 on 2025-01-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_bioinfouser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolerequest',
            name='status',
            field=models.CharField(choices=[('A', 'Accepté'), ('P', 'Attente'), ('D', 'Refusé')], default='P', max_length=1),
        ),
    ]
