# Generated by Django 5.1.3 on 2025-01-21 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rolerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolerequest',
            name='date_submitted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de soumission'),
            preserve_default=False,
        ),
    ]
