# Generated by Django 5.1.3 on 2025-01-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rolerequest_date_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bioinfouser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='bioinfouser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
