# Generated by Django 5.1.3 on 2025-01-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_bioinfouser_is_admin_bioinfouser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bioinfouser',
            name='is_superuser',
        ),
    ]
