# Generated by Django 5.1.3 on 2025-02-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_bioinfouser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinfouser',
            name='last_name',
            field=models.CharField(default='Marley', max_length=32, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='bioinfouser',
            name='name',
            field=models.CharField(default='Bob', max_length=32, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='bioinfouser',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='numero de téléphone'),
        ),
    ]
