# Generated by Django 5.1.3 on 2025-02-06 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_bioinfouser_last_name_bioinfouser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinfouser',
            name='last_name',
            field=models.CharField(default='Non renseigné', max_length=32, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='bioinfouser',
            name='name',
            field=models.CharField(default='Non renseigné', max_length=32, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='bioinfouser',
            name='numero',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
