# Generated by Django 5.1.3 on 2025-02-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.TextField()),
                ('species', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeneProtein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sequence', models.TextField()),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genes_proteins', to='search.genome')),
            ],
        ),
    ]
